'use strict';
var angular = require('angular');
angular.module("lionHeart", []);
require('./scripts/config/main.js');
require('./scripts/controllers/mainCtrl.js');
require('./scripts/controllers/productCtrl.js');
require('./scripts/controllers/signUpFormCtrl.js');
require('./scripts/directives/signup.js');
require('./scripts/directives/products.js');
require('./scripts/controllers/loginCtrl.js');
require('./scripts/directives/login.js');
require('./scripts/controllers/purchaseConfirmationCtrl.js');
require('./scripts/directives/purchaseConfirmation.js');
require('./scripts/controllers/confirmationPageCtrl.js');
require('./scripts/directives/confirmationPage.js');
require('./scripts/controllers/cartCtrl.js');
require('./scripts/directives/cart.js');
require('./scripts/controllers/profileCtrl.js');
require('./scripts/directives/profile.js');
require('./scripts/controllers/orderHistoryCtrl.js');
require('./scripts/directives/orderHistory.js');
require('./scripts/controllers/categoryCtrl.js');
require('./scripts/directives/category.js');
require('./scripts/controllers/menuCtrl.js');
require('./scripts/directives/menu.js');
require('./scripts/controllers/bioCtrl.js');
require('./scripts/directives/bio.js');
require('./scripts/controllers/category.searchCtrl.js');
require('./scripts/controllers/category.categoriesCtrl.js');
require('./scripts/directives/category.categoriesCtrl.js');
require('./scripts/controllers/category.paintingsCtrl.js');
require('./scripts/controllers/category.printsCtrl.js');
require('./scripts/controllers/category.graphicsCtrl.js');
require('./scripts/controllers/category.upcycleCtrl.js');
require('./scripts/controllers/category.skateboardsCtrl.js');
require('./scripts/controllers/category.stickersCtrl.js');
require('./scripts/controllers/indexCtrl.js');
require('./scripts/controllers/profile.dashboardCtrl.js');
require('./scripts/controllers/profile.dashboard.editCtrl.js');
require('./scripts/controllers/singleItemCtrl.js');
require('./scripts/controllers/cart.checkoutCtrl.js');
require('./scripts/controllers/admin.productsCtrl.js');
require('./scripts/controllers/admin.postsCtrl.js');
require('./scripts/controllers/admin.usersCtrl.js');
require('./scripts/controllers/adminCtrl.js');
require('./scripts/controllers/portfolioCtrl.js');
require('./scripts/controllers/cart.confirmationCtrl.js');



require('./scripts/services/dataService.js');
require('./scripts/services/functionService.js');
require('./scripts/services/eraseCartService.js');
